export const HTTP_STATUS_CODES = {
    "HTTP_RESOURCE_CREATED": 201,
    "INTERNAL_SERVER_ERROR":500,
    "HTTP_OK":200,
    "BAD_REQUEST": 400,
    "DUPLICATE_RESOURCE": 409,
    "HTTP_ACCEPTED": 202,
    "HTTP_CONTENT_NOT_FOUND": 204
}